### ISSUE TITLE
Incompatible Python versions causing TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by aratelle-hepeng** [sayyid5416/pyinstaller#11]
The readme example is Python 3.6:
https://github.com/sayyid5416/pyinstaller/blame/454cc5f88cbfd6a1f7f5e6b9b96a0216be7f1720/README.md#L111

The code uses features introduced in Python 3.9:
https://github.com/sayyid5416/pyinstaller/blame/454cc5f88cbfd6a1f7f5e6b9b96a0216be7f1720/src/mods.py#L60

The discrepancy causes the following error:
["TypeError: 'type' object is not subscriptable"](https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature)

The easy fix for the discrepancy would be to use Python >=3.9 in the example, or you may want to consider using different import options to make the code compatible.

**Comment by sayyid5416** [comment]
Yes, you are right. I'll see what I can do.
