### ISSUE TITLE
Add input option to specify PyInstaller version

### ISSUE THREAD

**Issue by jonata** [sayyid5416/pyinstaller#12]
It would be good to being able to choose the PyInstaller version, as in some cases where the latest version is not the best.

**Comment by sayyid5416** [comment]
@jonata Actually, I'm a little busy right now, so it could take me a while to implement this. It's pretty easy to implement, if you want you can open a PR, and I will merge it.

**Comment by sayyid5416** [comment]
this has been added in #13
