### ISSUE TITLE
Merging fork

### ISSUE THREAD

**Issue by lrq3000** [sayyid5416/pyinstaller#15]
There is a fork with several very useful features such as being able to pass arguments to pyInstaller, I suggest it to be merged here before the codebases differ too much (easier now than later): https://github.com/Martin005/pyinstaller-action

**Comment by sayyid5416** [comment]
You can already pass arguments to pyinstaller using `options` input. [Check here](https://github.com/sayyid5416/pyinstaller?tab=readme-ov-file#-available-inputs).

**Comment by sayyid5416** [comment]
If there is any other feature you want from there, ask him to create a PR with only necessary code.
