### ISSUE TITLE
Node.js 16 actions are deprecated for some dependency actions

### ISSUE THREAD

**Issue by malomehi** [sayyid5416/pyinstaller#17]
Hi,

I am seeing this warning in my actions builds:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4, actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

Are you planning to use latest versions of these dependencies in future versions?

Also, `action/upload-artifact@v4` cannot be used for any artifact uploaded with `actions/upload-artifact@v3`, it is in the [breaking changes](https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes).

Thanks!

**Comment by sayyid5416** [comment]
I'm currently busy nowadays, but you're free to open a PR, I'll merge it.
