### ISSUE TITLE
Artifact name clash when creating more than one executable from a `.py` spec file

### ISSUE THREAD

**Issue by mfreeborn** [sayyid5416/pyinstaller#22]
When creating and uploading an executable using a `.py` spec file, the action uploads a spec file called `Generated spec file`. The problem is, when creating multiple executables, for example using a matrix action with multiple operating systems, multiple spec files of the same name are created.

Consequently, the action fails with this message: `Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`

The actual executable is still uploaded (assuming it's been given a unique name), I presume the executable gets uploaded first before the task crashes out trying to upload the second spec file.

**Comment by sayyid5416** [comment]
Thanks for reporting. It indeed is issue with conflicting names because spec file is hard coded with name "Generated spec file".

Also, you are correct, executable gets uploaded first.

**Comment by sayyid5416** [comment]
@mfreeborn Can you test if this fixes the issue?

```
uses: sayyid5416/pyinstaller@test
```

**Comment by mfreeborn** [comment]
Ah, I see you changed it so that it takes the `--name` option the
pyinstaller command. Given that the issue is file names, it's actually the
`upload_exe_with_name` parameter that the developer must ensure is unique.
Is it possible to just name the spec file
`f"{upload_exe_with_name_value}.spec"` (in pseudo-python)? That way it is
guaranteed to be unique, because, as I say, the developer has already
ensured that `upload_exe_with_name` is already unique so that there aren't
name clashes with the executable files.

**Comment by sayyid5416** [comment]
Yeah sure why not, try and report

**Comment by mfreeborn** [comment]
I don't see any changes in the `test` branch yet, but what I mean is changing [this line](https://github.com/sayyid5416/pyinstaller/blob/dbcc2db65863a3ac728cfe23ce3e971c145d91a6/action.yml#L133) to :

```yaml
name: ${{ inputs.upload_exe_with_name }}.spec
```

**Comment by sayyid5416** [comment]
Changed.

**Comment by sayyid5416** [comment]
@mfreeborn changed as requested. You can now test if everything is working fine,

**Comment by mfreeborn** [comment]
That's working great now, thanks!
