### ISSUE TITLE
[Question]: supported options for 'python_arch' ?

### ISSUE THREAD

**Issue by imxade** [sayyid5416/pyinstaller#24]

**Comment by imxade** [comment]
https://github.com/actions/setup-python?tab=readme-ov-file#supported-architectures

**Comment by sayyid5416** [comment]
Have you found the answer?

**Comment by imxade** [comment]
@sayyid5416 yeah that link.
A mention in readme would help.

**Comment by sayyid5416** [comment]
Already [there](https://github.com/sayyid5416/pyinstaller?tab=readme-ov-file#-available-inputs)

**Comment by imxade** [comment]
> Already [there](https://github.com/sayyid5416/pyinstaller?tab=readme-ov-file#-available-inputs)

It only mentions x64

**Comment by sayyid5416** [comment]
> > Already [there](https://github.com/sayyid5416/pyinstaller?tab=readme-ov-file#-available-inputs)
> 
> It only mentions x64

x64 is default one. You can use anyone you want. That's why it's called "input"

**Comment by imxade** [comment]
> > 
> 
> x64 is default one. You can use anyone you want. That's why it's called "input"

I mean supported options other than x64 isn't mentioned in the readme
