### ISSUE TITLE
Unnecessary error while compiling

### ISSUE THREAD

**Issue by memeLordo** [sayyid5416/pyinstaller#27]
![изображение](https://github.com/user-attachments/assets/b9a2177a-0b81-44d1-afe1-e1b96e8fab4a)
It happens when I choose to use `.py` instead of `.spec` file.

**Comment by sayyid5416** [comment]
I'll take a look at it, but tomorrow.

**Comment by sayyid5416** [comment]
@memeLordo can you send me complete logs? or the link to logs?

**Comment by memeLordo** [comment]
Sure.
https://github.com/memeLordo/telegram-message-search-tool/actions/runs/10889163312/job/30215194409

**Comment by memeLordo** [comment]
I assume that pyinstaller executes the .py file and creates artifacts, which are uploaded, buth the path is assigned to
${{ --name }}.spec file, which couldn't be found, because it wasn't created in a first place.

**Comment by sayyid5416** [comment]
> because it wasn't created in a first place.

@memeLordo why was it not created?

**Comment by sayyid5416** [comment]
> Sure. https://github.com/memeLordo/telegram-message-search-tool/actions/runs/10889163312/job/30215194409

this link is giving error 404

**Comment by sayyid5416** [comment]
@memeLordo It's been a long time without any response.
