### ISSUE TITLE
[ENHANCEMENT] Add --collect*

### ISSUE THREAD

**Issue by Nackophilz** [sayyid5416/pyinstaller#8]
Hi there!

I wanted to know, would it be possible, or is it planned to add the option included in py installer namely the "--collect-all"?

It's very useful, especially for the pyGithub and plexAPI module for one of my projects, and when I add it it doesn't recognize it :)

**Comment by sayyid5416** [comment]
@Nackophilz I'll take a look at it.

**Comment by Nackophilz** [comment]
Thank for your answer @sayyid5416 ! :)

**Comment by Nackophilz** [comment]
I created a pull request to add it

Simultaneously, I added a modification to another fork that had added collect data :)
